function [polar, cruzeiro, Vy, VDM, VAM, Vvm, Vrm] = analisar_fase(W, Zp, dT, heli, Vc_fpm, V_vento, plotar, pasta_fig, fase_label)
    % ANALISAR_FASE  Roda a polar vertical e o balanço de cruzeiro para um
    % dado estado de peso/altitude, e empacota os dois em structs para o JSON.
    %
    % Saídas:
    %   polar     struct com W, Zp, V_tas, vZ, vZ_auto e velocidades notáveis
    %   cruzeiro  struct com V_tas, curvas P_tot/P_ind/P_perf/P_par/P_misc,
    %             VDM, VAM e V_max
    %   Vy, VDM, VAM, Vvm, Vrm  velocidades notáveis [kt]

    if nargin < 8, pasta_fig  = ''; end
    if nargin < 9, fase_label = ''; end

    [V_pol, ~, vZ, Vy, Vzmax, Vvm, Vrm, vZ_auto, VrM] = ...
        Polar_Velocidade(W, Zp, dT, heli, Vc_fpm, plotar, [], V_vento, pasta_fig, fase_label);

    [VDM, VAM, V_max, V_tas, P_tot_hp, P_ind, P_perf, P_par, P_misc] = ...
        Analise_Velocidades_Cruzeiro(W, Zp, dT, heli, V_vento, plotar, pasta_fig, fase_label);

    polar = struct('W', W, 'Zp', Zp, 'dT', dT, ...
                   'V_tas',   V_pol,   ...
                   'vZ',      vZ,      ...
                   'vZ_auto', vZ_auto, ...
                   'Vy',      Vy,      ...
                   'Vzmax',   Vzmax,   ...
                   'VrM',     VrM,     ...
                   'Vvm',     Vvm,     ...
                   'Vrm',     Vrm);

    cruzeiro = struct('W', W, 'Zp', Zp,                             ...
                      'V_tas',    V_tas,   'P_tot_hp',  P_tot_hp,   ...
                      'P_ind_hp', P_ind,   'P_perf_hp', P_perf,     ...
                      'P_par_hp', P_par,   'P_misc_hp', P_misc,     ...
                      'VDM', VDM, 'VAM', VAM, 'V_max', V_max);
end
