function fase = atribui_fase(nome, vel, potencias, comb)
    fase = struct( ...
        'nome',   nome, ...
        'P_ind',  potencias.P_ind, ...
        'P_perf', potencias.P_perf, ...
        'P_par',  potencias.P_par, ...
        'P_vert', potencias.P_vert, ...
        'P_misc', potencias.P_misc, ...
        'P_tot',  potencias.P_tot, ...
        'vel',    vel, ...
        'comb',   comb);
end
